server:
  port: 8082
spring:
  datasource:
    url: 'jdbc:mysql://${DB_URL:localhost}:3306/${DB_NAME:test}?serverTimezone=UTC'
    username: '${DB_USER:root}'
    password: '${DB_PASSWORD:root123456}'
    # hikaricp 配置
    hikari:
      jdbc-url: 'jdbc:mysql://${DB_URL:localhost}:3306/${DB_NAME:test}?serverTimezone=UTC'
      username: '${DB_USER:root}'
      password: '${DB_PASSWORD:root123456}'
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        format_sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    lettuce:
      shutdown-timeout: 3000
      pool:
        max-active: 32
        max-wait: 300
        max-idle: 16
        min-idle: 8
  quartz:
  #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
    #初始化表结构
#    jdbc:
#      initialize-schema: ALWAYS
